# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# DATABASE - MYSQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=2692005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
jwt.secret=CRS_AUTH_SERVICE_SECRET_KEY_2026_VU_DUY_TIEN_AUTHENTICATION
jwt.expiration-ms=86400000