server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/course_data?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=2692005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT - phải giống auth-service
jwt.secret=CRS_AUTH_SERVICE_SECRET_KEY_2026_VU_DUY_TIEN_AUTHENTICATION